apiVersion: v1
kind: Service
metadata:
  namespace: format-transformer-domain-apps
  name: format-transformer-panel-service
  labels:
    app: format-transformer-panel
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: format-transformer-panel
