apiVersion: apps/v1
kind: Deployment
metadata:
  name: format-transformer-persister-deployment
  namespace: ft-backend
  labels:
    app: format-transformer-persister
spec:
  replicas: 1
  selector:
    matchLabels:
      app: format-transformer-persister
  template:
    metadata:
      labels:
        app: format-transformer-persister
    spec:
      containers:
      - name: format-transformer-persister
        image: meksula/format-transformer-persister:v1.0.1
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_PROFILE_NAME
          valueFrom:
            configMapKeyRef:
              name: format-transformer-cm
              key: spring-profile-name
        - name: MESSAGE_BROKER_HOST
          valueFrom:
            configMapKeyRef:
              name: format-transformer-cm
              key: message-broker-host
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: format-transformer-cm
              key: database-host
      restartPolicy: Always
