apiVersion: apps/v1
kind: Deployment
metadata:
  name: format-transformer-stats-deployment
  namespace: ft-backend
  labels:
    app: format-transformer-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: format-transformer-stats
  template:
    metadata:
      labels:
        app: format-transformer-stats
    spec:
      containers:
      - name: format-transformer-stats
        image: meksula/format-transformer-stats:v1.0.5-rc
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_PROFILE_NAME
          valueFrom:
            configMapKeyRef:
              name: format-transformer-cm
              key: spring-profile-name
        - name: FORMAT_TRANSFORMER_PERSISTER_HOST
          valueFrom:
            configMapKeyRef:
              name: format-transformer-microservices-hosts
              key: format-transformer-persister-host
        - name: FORMAT_TRANSFORMER_PERSISTER_PORT
          valueFrom:
            configMapKeyRef:
              name: format-transformer-microservices-hosts
              key: format-transformer-persister-port
      restartPolicy: Always
